# Site settings
title: "РАДАР УКРАЇНИ"
baseurl: ""          # Change if deploying to a subpath (e.g. "/Radarka")
url: ""              # Your domain, e.g. https://username.github.io

# Build settings
enable_plugins: []   # No additional plugins needed
